package icsutil

import "testing"

func TestMergeRRule(t *testing.T) {
	cases := []struct {
		existing, incoming, want string
	}{
		{"", "FREQ=WEEKLY", "FREQ=WEEKLY"},
		{"FREQ=WEEKLY;BYDAY=MO,WE", "FREQ=WEEKLY;BYDAY=MO,WE", "FREQ=WEEKLY;BYDAY=MO,WE"},
		{"FREQ=WEEKLY;BYDAY=MO,WE", "FREQ=WEEKLY", "FREQ=WEEKLY;BYDAY=MO,WE"},
		{"FREQ=WEEKLY;INTERVAL=2;BYDAY=MO", "FREQ=WEEKLY", "FREQ=WEEKLY;BYDAY=MO"},
		{"FREQ=WEEKLY;INTERVAL=2;BYDAY=MO", "FREQ=WEEKLY;INTERVAL=3", "FREQ=WEEKLY;INTERVAL=3;BYDAY=MO"},
		{"FREQ=WEEKLY;UNTIL=20260828T215959Z;BYDAY=MO", "FREQ=WEEKLY;UNTIL=20260828", "FREQ=WEEKLY;UNTIL=20260828T215959Z;BYDAY=MO"},
		{"FREQ=WEEKLY;UNTIL=20260828T215959Z;BYDAY=MO", "FREQ=WEEKLY;UNTIL=20260901", "FREQ=WEEKLY;UNTIL=20260901;BYDAY=MO"},
		{"FREQ=WEEKLY;COUNT=10;BYDAY=MO", "FREQ=WEEKLY;COUNT=4", "FREQ=WEEKLY;COUNT=4;BYDAY=MO"},
		{"FREQ=WEEKLY;COUNT=10;BYDAY=MO", "FREQ=WEEKLY", "FREQ=WEEKLY;BYDAY=MO"},
		{"FREQ=WEEKLY;WKST=SU;BYDAY=MO", "FREQ=WEEKLY", "FREQ=WEEKLY;WKST=SU;BYDAY=MO"},
		{"FREQ=WEEKLY;BYDAY=MO,WE", "FREQ=DAILY", "FREQ=DAILY"},
		{"FREQ=WEEKLY;BYDAY=MO", "", ""},
	}
	for _, tc := range cases {
		if got := mergeRRule(tc.existing, tc.incoming); got != tc.want {
			t.Errorf("mergeRRule(%q, %q)=%q want %q", tc.existing, tc.incoming, got, tc.want)
		}
	}
}
